security:
  user:
    name: admin
    password: admin
  basic:
    enabled: false

spring:
  output.ansi.enabled: ALWAYS
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:postgresql://${docker.host}/postgres
    username: postgres
    password: pass
    testOnBorrow: true
    validationQuery: SELECT 1

docker:
  host: 192.168.99.100
  endpoint: http://${docker.host}:2375